CREATE TABLE "GAB_3858_LOT_INFO"(
 "PCK_NO" CHAR(7),
 "ORDER_NO" CHAR(7),
 "ORDER_SHIP_NO" CHAR(4),
 "ORDER_REC" CHAR(4),
 "PART" CHAR(20),
 "LOT" CHAR(15),
 "BIN" CHAR(6),
 "HEAT" CHAR(15),
 "SERIAL" CHAR(30),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "LOC" CHAR(2),
 "STAT" CHAR(1)
);
CREATE NOT MODIFIABLE INDEX "GAB_LOT_INFOSK00" ON "GAB_3858_LOT_INFO"("PCK_NO", "ORDER_NO", "ORDER_REC", "ORDER_SHIP_NO");
