CREATE TABLE "GAB_3858_LOT_LBHS"(
 "TERMINAL" CHAR(3) NOT NULL ,
 "ID" CHAR(3) NOT NULL ,
 "ORDER_REC" CHAR(4),
 "PART" CHAR(20) NOT NULL ,
 "LOCATION" CHAR(2),
 "LOT" CHAR(15),
 "BIN" CHAR(6),
 "HEAT" CHAR(15),
 "SERIAL" CHAR(30),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "CODE_TRANSACTION" CHAR(3),
 "SEQUENCE" CHAR(6),
 "CHK" CHAR(1)
);